# Generated by Django 3.2 on 2021-05-30 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20210530_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('option_1', models.CharField(max_length=50, unique=True)),
                ('option_2', models.CharField(default=None, max_length=50, unique=True)),
                ('option_3', models.CharField(default=None, max_length=50, unique=True)),
                ('option_4', models.CharField(default=None, max_length=50, unique=True)),
                ('which_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
