# Generated by Django 3.2 on 2021-05-30 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210530_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_2',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_3',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_4',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
