# Generated by Django 3.2 on 2021-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20210530_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option_2',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_3',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_4',
            field=models.CharField(blank=True, default=None, max_length=50, unique=True),
        ),
    ]
