# Generated by Django 3.2 on 2021-06-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20210530_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_1',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='option_4',
        ),
        migrations.AlterField(
            model_name='answer',
            name='which_question',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quizapp.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(db_index=True)),
                ('which_question', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quizapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.answers'),
        ),
    ]
