# Generated by Django 3.2 on 2021-06-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20210605_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='category',
            new_name='answers_list',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='which_question',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='quizapp.choice'),
        ),
    ]
