# Generated by Django 3.2 on 2021-06-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0011_auto_20210605_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id',
            field=models.SlugField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.SlugField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.SlugField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
