# Generated by Django 3.2 on 2021-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0012_auto_20210605_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers_list',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='which_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.AddField(
            model_name='answers',
            name='answers',
            field=models.ManyToManyField(to='quizapp.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='quizapp.Choice'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quizapp.Question'),
        ),
    ]
