# Generated by Django 3.2 on 2021-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0013_auto_20210605_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
