# Generated by Django 3.2 on 2021-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0015_choice_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.SlugField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
